/** @type {import('tailwindcss').Config} */
export default {
  content: ['./index.html', './src/**/*.{js,jsx}'],
  darkMode: 'class',
  theme: {
    extend: {
      colors: {
        'inverse-primary': '#006786',
        'on-background': '#dfe4ff',
        'on-primary': '#00445a',
        'surface': '#090e1c',
        'inverse-surface': '#faf8ff',
        'surface-dim': '#090e1c',
        'on-secondary-fixed-variant': '#5a3bdd',
        'on-primary-container': '#00394d',
        'surface-bright': '#202b4b',
        'primary-container': '#00c4fd',
        'on-surface-variant': '#a0aace',
        'inverse-on-surface': '#505466',
        'on-secondary-fixed': '#3d08c1',
        'on-primary-fixed-variant': '#004b63',
        'secondary-container': '#24007f',
        'on-surface': '#dfe4ff',
        'surface-variant': '#1b2541',
        'on-tertiary-container': '#005a3c',
        'surface-container-lowest': '#000000',
        'secondary-fixed-dim': '#d7ceff',
        'primary-fixed': '#56ceff',
        'secondary-fixed': '#e5deff',
        'on-error-container': '#ff9993',
        'background': '#090e1c',
        'error': '#ff716c',
        'secondary-dim': '#7459f7',
        'surface-container-highest': '#1b2541',
        'on-tertiary-fixed': '#00452d',
        'on-tertiary': '#006443',
        'surface-container': '#11192e',
        'primary-dim': '#00b6ea',
        'outline-variant': '#3d4766',
        'secondary': '#c9bfff',
        'on-error': '#490006',
        'tertiary-fixed-dim': '#58e7ab',
        'primary': '#62d0ff',
        'tertiary': '#9bffce',
        'surface-container-high': '#161f38',
        'outline': '#6b7496',
        'on-primary-fixed': '#002c3b',
        'on-tertiary-fixed-variant': '#006544',
        'on-secondary-container': '#a596ff',
        'on-secondary': '#3e0bc2',
        'surface-container-low': '#0c1325',
        'tertiary-fixed': '#69f6b8',
        'surface-tint': '#62d0ff',
        'error-container': '#8a1a1e',
        'primary-fixed-dim': '#00c1f9',
        'error-dim': '#c94947',
        'tertiary-dim': '#58e7ab',
        'tertiary-container': '#69f6b8',
        'success': '#9bffce',
      },
      fontFamily: {
        headline: ['Noto Serif', 'serif'],
        body: ['Inter', 'sans-serif'],
        label: ['Inter', 'sans-serif'],
      },
    },
  },
  plugins: [],
}
